In [ ]:
# Importing Dependencies

In [2]:
import pandas as pd
import os
import glob

In [3]:
dataset = [pd.read_csv(f) for f in glob.glob(r"C:\Users\user\Downloads\CodeConnect_DataAnalyticsModule_participant_data\*.csv")]

In [5]:
dataset

[      customer_id       full_name                        email         phone  \
 0         C000001      Nida Memon     nida.memon6133@yahoo.com  0343-4328042
 1         C000002   rizwan ansari  rizwan.ansari7047@gmail.com   03292755530
 2         C000003       Noor Baig       noor.baig763@gmail.com   330 2812162
 3         C000004   Naveed Hashmi  naveed.hashmi9719@gmail.com   03128373694
 4         C000005   Mahnoor Mirza  mahnoor.mirza5501@yahoo.com   03251346045
 ...           ...             ...                          ...           ...
 44995     C044996   Kashif Abbasi  KASHIF.ABBASI9556@GMAIL.COM   03424368175
 44996     C044997      Sana Javed   SANA.JAVED1711@HOTMAIL.COM  0334-6227664
 44997     C044998     Anum Abbasi    anum_abbasi6678@gmail.com   03184589695
 44998     C044999      Rabia Raza     rabia.raza3918@gmail.com           NaN
 44999     C045000       iqra baig      IQRA.BAIG3854@GMAIL.COM  0313 5225659

       gender registration_date  city_id  birth_year
 0          F        2024-02-04    614.0      1996.0
 1          m        03/02/2025    310.0      1977.0
 2          F        2024-01-31    347.0      1999.0
 3          M        2024-07-18    570.0      1985.0
 4          F        2024-04-07    614.0      1989.0
 ...      ...               ...      ...         ...
 44995      m        2023-08-29    573.0      2000.0
 44996      F        2025-03-28    119.0      2003.0
 44997      F        2025-02-06    401.0      1996.0
 44998      F        2025-02-09    614.0         NaN
 44999      F        Jun 6 2024    390.0      2007.0

 [45000 rows x 8 columns],
      city_id            city            province   region  latitude  \
 0          1       PurPurPur               Sindh    South   26.1297
 1          2   SaraiTandoKot              Punjab  Central   31.3893
 2          3  WalaSaraiBasti              Punjab  Central   31.8080
 3          4    ShahChakAbad         Balochistan    South   28.2820
 4          5         RahKila         Balochistan    South   26.6041
 ..       ...             ...                 ...      ...       ...
 645      646      AliKilaGul              Punjab  Central   32.3267
 646      647         DeraAli              Punjab  Central   31.9504
 647      648        GarhDhok  Khyber Pakhtunkhwa    North   34.9987
 648      649       WalaNagar               Sindh    South   27.5591
 649      650    MianKilaThal              Punjab  Central   30.7896

      longitude population_tier
 0      68.2655          Tier-3
 1      73.2073          Tier-3
 2      71.8958          Tier-3
 3      66.0572          Tier-3
 4      66.4652          Tier-3
 ..         ...             ...
 645    72.5229          Tier-3
 646    72.2453          Tier-3
 647    71.7371          Tier-3
 648    68.1782          Tier-3
 649    72.9540          Tier-3

 [650 rows x 7 columns],
         order_id customer_id   order_date order_status  ship_city_id  \
 0       O0106517     C042364   2025-02-04     DELIVERD         316.0
 1       O0129677     C022887   2025-04-06    Delivered         347.0
 2       O0083748     C010022  Nov 23 2024    Delivered         281.0
 3       O0027756     C032262   May 2 2024    Delivered         347.0
 4       O0119576     C035932   2025-03-14    Completed         450.0
 ...          ...         ...          ...          ...           ...
 163195  O0014965     C033177   2024-03-18    DELIVERED         391.0
 163196  O0136734     C021700   28/04/2025    Delivered         643.0
 163197  O0051278     C005298   2024-08-04    Cancelled         450.0
 163198  O0029625     C036720   2024-05-11     Complete          86.0
 163199  O0032135     C009633   2024-05-22    Delivered         601.0

        order_total discount_code     channel
 0             5206           NaN     Website
 1              675           NaN         App
 2             2362           NaN         Web
 3             5858           NaN         App
 4            35935        SAVE25  Mobile Web
 ...            ...           ...         ...
 163195        3271           NaN         web
 163196         374           NaN  Mobile App
 163197        7287           NaN  Mobile web
 163198       13309        SAVE10  Mobile Web
 163199         506           NaN         Web

 [163200 rows x 8 columns],
        order_item_id  order_id product_id seller_id quantity unit_price  \
 0         OI00000001  O0000001     P02548     S0310        1  Rs. 2,290
 1         OI00000002  O0000001     P01857     S0197        1       5850
 2         OI00000003  O0000002     P01761     S0243        1       1900
 3         OI00000004  O0000003     P00334     S0387        1       2180
 4         OI00000005  O0000003     P02889     S0223        1       2100
 ...              ...       ...        ...       ...      ...        ...
 315138    OI00315139  O0159998     P00962     S0063        2        543
 315139    OI00315140  O0159998     P00737     S0249        1       2424
 315140    OI00315141  O0159999     P02500     S0203        1        616
 315141    OI00315142  O0159999     P01598     S0175        2       1337
 315142    OI00315143  O0160000     P02151     S0124        1       1233

         discount_amount
 0                   0.0
 1                   0.0
 2                   0.0
 3                   0.0
 4                   0.0
 ...                 ...
 315138              0.0
 315139              0.0
 315140              0.0
 315141              0.0
 315142            493.0

 [315143 rows x 7 columns],
          payment_id  order_id payment_method payment_status amount  \
 0       PAY00048624  O0047146            COD           Paid   1270
 1       PAY00084629  O0082098       JazzCash           Paid   3747
 2       PAY00140975  O0136814     Debit Card           Paid   8745
 3       PAY00153531  O0149032            COD      Cancelled   2120
 4       PAY00051260  O0049688            COD       Complete  14892
 ...             ...       ...            ...            ...    ...
 168106  PAY00158553  O0153920           Card           Paid   8733
 168107  PAY00030780  O0029830            COD      Cancelled  44354
 168108  PAY00115673  O0112268       JazzCash           Paid   1637
 168109  PAY00084830  O0082297      EasyPaisa           Paid  22170
 168110  PAY00143028  O0138815       JazzCash       Complete   3641

        payment_date
 0        2024-07-19
 1        2024-11-17
 2        2025-04-29
 3        2025-06-15
 4        2024-08-03
 ...             ...
 168106   13/06/2025
 168107          NaN
 168108   2025-02-23
 168109   2024-11-17
 168110   2025-05-05

 [168111 rows x 6 columns],
      product_id                        product_name                 category  \
 0        P00001            MobiPro USB-C Cable L740     Mobile & Accessories
 1        P00002           NexusChoice Sneakers I796                 Footwear
 2        P00003                 Zeta Polo Shirt T44                  Fashion
 3        P00004            SporPro Cricket Bat T947                   Sports
 4        P00005          AutoPro Tyre Inflator E655               Automotive
 ...         ...                                 ...                      ...
 3195     P03196              Orion Moisturizer R840   Beauty & Personal Care
 3196     P03197  NexusChoice Denim Jeans P901 - New                  Fashion
 3197     P03198         Generic Planner O741 (2024)      BOOKS & STATIONERY
 3198     P03199            Orion Hoodie K183 (2024)                  fashion
 3199     P03200      Generic Lipstick T393 Original  Beauty & Personal Care

            sub_category        brand list_price  cost_price  weight_kg  \
 0     Mobile Essentials      MobiPro        980       577.0       0.39
 1       Footwear Basics  NexusChoice       6990         NaN       0.98
 2       Fashion Premium         Zeta       1960      1122.0      -1.00
 3         Sports Basics      SporPro       2090      1366.0       0.99
 4     Automotive Basics      AutoPro       4500      3156.0       1.37
 ...                 ...          ...        ...         ...        ...
 3195      Beauty Basics          NaN       3391      1634.0       0.38
 3196    Fashion Premium  NexusChoice       1582       928.0       0.29
 3197                NaN      Generic        687       485.0       0.80
 3198     Fashion Basics        Orion       1968      1257.0        NaN
 3199  Beauty Essentials      Generic    Rs. 380       209.0       0.64

      seller_id
 0        S0411
 1        S0130
 2        S0322
 3        S0083
 4        S0065
 ...        ...
 3195     S0306
 3196     S0119
 3197     S0070
 3198     S0405
 3199     S0260

 [3200 rows x 9 columns],
       return_id order_item_id return_date           return_reason  \
 0       R000001    OI00000155  2024-01-06        Not as described
 1       R000002    OI00000220  2024-01-07          Size/fit issue
 2       R000003    OI00000308  2024-01-07                     NaN
 3       R000004    OI00000553  2024-01-07           Quality issue
 4       R000005    OI00000397  2024-01-08           Quality issue
 ...         ...           ...         ...                     ...
 16043   R016044    OI00310831  2025-06-30          Size/fit issue
 16044   R016045    OI00310930  2025-06-30            Changed mind
 16045   R016046    OI00310978  2025-06-30                     NaN
 16046   R016047    OI00312268  2025-06-30  different from picture
 16047   R016048    OI00312334  2025-06-30                     NaN

       return_status refund_amount
 0          Refunded          1020
 1          REFUNDED          1558
 2          Approved          3050
 3          Refunded           712
 4          Refunded          1685
 ...             ...           ...
 16043      approved          9352
 16044      Refunded          4848
 16045      Rejected             0
 16046      Refunded           817
 16047      Approved          2434

 [16048 rows x 6 columns],
     seller_id           seller_name   join_date seller_tier  city_id  rating
 0       S0001    Karachi Traders 84  2023-07-17        Gold      597     4.1
 1       S0002  Crown Collection 32   2020-02-14      Silver       86     4.1
 2       S0003          Metro Mart 5  2022-10-16      Bronze      450     3.9
 3       S0004   Karachi Brothers 38  2019-12-31      Bronze      597     4.3
 4       S0005      Metro Traders 88         NaN      Bronze      614    11.0
 ..        ...                   ...         ...         ...      ...     ...
 415     S0416      Royal Traders 46  2021-03-10      Bronze      456     4.3
 416     S0417      Best Brothers 42         NaN        Gold       86     NaN
 417     S0418     Royal Solutions 1  27/01/2022      Bronze      347     4.5
 418     S0419         Smart Mart 74  2023-11-13         NaN      630     4.3
 419     S0420        Royal Store 72  2022-02-21      Bronze      535     4.1

 [420 rows x 6 columns],
        shipment_id  order_id      courier shipped_date delivered_date  \
 0       SH00000001  O0000001          M&P   2024-01-02     2024-01-06
 1       SH00000002  O0000002     Leopards   2024-01-02     2024-01-04
 2       SH00000003  O0000003     Leopards   2024-01-02     2024-01-05
 3       SH00000004  O0000004       POSTEX   2024-01-02     2024-01-11
 4       SH00000005  O0000005  TCS Express   2024-01-02     2024-01-05
 ...            ...       ...          ...          ...            ...
 151223  SH00151224  O0159995          MnP   2025-06-30            NaN
 151224  SH00151225  O0159996       PostEx   2025-07-01            NaN
 151225  SH00151226  O0159997         Trax   2025-07-01            NaN
 151226  SH00151227  O0159998          m&p   2025-07-02            NaN
 151227  SH00151228  O0160000          TCS   2025-07-01            NaN

         shipping_fee     delivery_status
 0              823.0            DELIVERD
 1              309.0           Delivered
 2              459.0           Delivered
 3             1050.0           Delivered
 4              624.0           delivered
 ...              ...                 ...
 151223         290.0          In Transit
 151224         713.0          In Transit
 151225        1000.0          In Transit
 151226         457.0          In Transit
 151227         378.0  Returned to Seller

 [151228 rows x 7 columns]]

In [ ]:
#STEP: 1- AUDIT ALL 9 FILES to record row counts, column types, nulls, exact duplicate rows, and duplicate IDs for every file

In [7]:
for i, df in enumerate(dataset):
    print(f"\n{'='*40}\nFILE {i}\n{'='*40}")
    print("Rows:", len(df))
    print("\nColumn types:\n", df.dtypes)
    print("\nNulls per column:\n", df.isnull().sum())
    print("\nExact duplicate rows:", df.duplicated().sum())

    id_cols = [c for c in df.columns if c.lower() == 'id'
               or c.lower().endswith('_id')]

    for col in id_cols:
        print(f"Duplicate {col} values:", df[col].duplicated().sum())

========================================
FILE 0
========================================
Rows: 45000

Column types:
 customer_id           object
full_name             object
email                 object
phone                 object
gender                object
registration_date     object
city_id              float64
birth_year           float64
dtype: object

Nulls per column:
 customer_id             0
full_name               0
email                1698
phone                3599
gender               2199
registration_date       0
city_id              2233
birth_year           4600
dtype: int64

Exact duplicate rows: 0
Duplicate customer_id values: 0
Duplicate city_id values: 44349

========================================
FILE 1
========================================
Rows: 650

Column types:
 city_id              int64
city                object
province            object
region              object
latitude           float64
longitude          float64
population_tier     object
dtype: object

Nulls per column:
 city_id             0
city                0
province           25
region              0
latitude           33
longitude          31
population_tier     0
dtype: int64

Exact duplicate rows: 0
Duplicate city_id values: 0

========================================
FILE 2
========================================
Rows: 163200

Column types:
 order_id          object
customer_id       object
order_date        object
order_status      object
ship_city_id     float64
order_total       object
discount_code     object
channel           object
dtype: object

Nulls per column:
 order_id              0
customer_id           0
order_date            0
order_status          0
ship_city_id       6516
order_total           0
discount_code    112059
channel               0
dtype: int64

Exact duplicate rows: 3200
Duplicate order_id values: 3200
Duplicate customer_id values: 129444
Duplicate ship_city_id values: 162549

========================================
FILE 3
========================================
Rows: 315143

Column types:
 order_item_id       object
order_id            object
product_id          object
seller_id           object
quantity            object
unit_price          object
discount_amount    float64
dtype: object

Nulls per column:
 order_item_id          0
order_id               0
product_id             0
seller_id              0
quantity               0
unit_price             0
discount_amount    31567
dtype: int64

Exact duplicate rows: 0
Duplicate order_item_id values: 0
Duplicate order_id values: 155143
Duplicate product_id values: 311057
Duplicate seller_id values: 314736

========================================
FILE 4
========================================
Rows: 168111

Column types:
 payment_id        object
order_id          object
payment_method    object
payment_status    object
amount            object
payment_date      object
dtype: object

Nulls per column:
 payment_id           0
order_id             0
payment_method       0
payment_status       0
amount               0
payment_date      5017
dtype: int64

Exact duplicate rows: 3296
Duplicate payment_id values: 3296
Duplicate order_id values: 8111

========================================
FILE 5
========================================
Rows: 3200

Column types:
 product_id       object
product_name     object
category         object
sub_category     object
brand            object
list_price       object
cost_price      float64
weight_kg       float64
seller_id        object
dtype: object

Nulls per column:
 product_id        0
product_name      0
category          0
sub_category    485
brand           392
list_price        0
cost_price      170
weight_kg       296
seller_id         0
dtype: int64

Exact duplicate rows: 0
Duplicate product_id values: 0
Duplicate seller_id values: 2793

========================================
FILE 6
========================================
Rows: 16048

Column types:
 return_id        object
order_item_id    object
return_date      object
return_reason    object
return_status    object
refund_amount    object
dtype: object

Nulls per column:
 return_id           0
order_item_id       0
return_date         0
return_reason    2390
return_status       0
refund_amount       0
dtype: int64

Exact duplicate rows: 0
Duplicate return_id values: 0
Duplicate order_item_id values: 0

========================================
FILE 7
========================================
Rows: 420

Column types:
 seller_id       object
seller_name     object
join_date       object
seller_tier     object
city_id          int64
rating         float64
dtype: object

Nulls per column:
 seller_id       0
seller_name     0
join_date      34
seller_tier    22
city_id         0
rating         33
dtype: int64

Exact duplicate rows: 0
Duplicate seller_id values: 0
Duplicate city_id values: 314

========================================
FILE 8
========================================
Rows: 151228

Column types:
 shipment_id         object
order_id            object
courier             object
shipped_date        object
delivered_date      object
shipping_fee       float64
delivery_status     object
dtype: object

Nulls per column:
 shipment_id            0
order_id               0
courier                0
shipped_date        5943
delivered_date     18841
shipping_fee        9145
delivery_status        0
dtype: int64

Exact duplicate rows: 0
Duplicate shipment_id values: 0
Duplicate order_id values: 0

In [ ]:
#STAGE: 2 - DATE VALIDATION to check unparseable dates, missing dates, dates outside the required range, and displays the invalid records.

In [9]:
for i, df in enumerate(dataset):
    date_cols = [c for c in df.columns if 'date' in c.lower()]
    print(f"\n{'='*50}\nFILE {i}\n{'='*50}")

    for col in date_cols:
        raw = df[col]
        dates = pd.to_datetime(
            raw, format='mixed', dayfirst=True, errors='coerce'
        )

        unparseable = raw.notna() & dates.isna()
        out_of_range = dates.notna() & (
            (dates < '2024-01-01') | (dates >= '2025-07-01')
        )

        print(f"\nColumn: {col}")
        print("Missing:", raw.isna().sum())
        print("Unparseable:", unparseable.sum())
        print("Out of range:", out_of_range.sum())

        if unparseable.any():
            print("Unparseable values:")
            print(raw[unparseable].unique()[:10])

        if out_of_range.any():
            print("Out-of-range values:")
            print(raw[out_of_range].unique()[:10])

==================================================
FILE 0
==================================================

Column: registration_date
Missing: 0
Unparseable: 252
Out of range: 8788
Unparseable values:
['2024-02-30' '2024-06-31' '2023-02-30' '2024-04-31' '2025-06-31'
 '2023-06-31' '2025-02-30' '00/00/2024' '00/00/2023' '00/00/2025']
Out-of-range values:
['2023-11-06' '2023-04-11' '2023-12-26' '2023-12-29' '2023-11-30'
 '2023-07-21' '2023-12-12' '2023-04-10' '2023-12-22' '13/11/2023']

==================================================
FILE 1
==================================================

==================================================
FILE 2
==================================================

Column: order_date
Missing: 0
Unparseable: 911
Out of range: 491
Unparseable values:
['00/00/2024' '2024-02-30' '2025-04-31' '2024-04-31' '2025-06-31'
 '2024-06-31' '00/00/2025' '2025-02-30' '2026-04-31' '2027-02-30']
Out-of-range values:
['2026-08-21' '2026-05-14' '2027-03-27' '2027-01-10' '2027-04-17'
 '2027-02-06' '09/10/2026' 'Nov 9 2026' '2027-06-06' '2026-06-05']

==================================================
FILE 3
==================================================

==================================================
FILE 4
==================================================

Column: payment_date
Missing: 5017
Unparseable: 871
Out of range: 793
Unparseable values:
['2024-02-30' '00/00/2025' '2025-06-31' '00/00/2024' '2025-02-30'
 '2024-06-31' '2024-04-31' '2025-04-31']
Out-of-range values:
['03/07/2025' '2025-07-04' '2025-07-01' '2025-07-05' '2025-07-03'
 '2025-07-02' 'Jul 4 2025' '10/07/2025' '04/07/2025' '2025-07-10']

==================================================
FILE 5
==================================================

==================================================
FILE 6
==================================================

Column: return_date
Missing: 0
Unparseable: 106
Out of range: 24
Unparseable values:
['00/00/2024' '2024-02-30' '2024-06-31' '2024-04-31' '2023-04-31'
 '2025-04-31' '2025-06-31' '00/00/2025' '2025-02-30']
Out-of-range values:
['2023-08-18' '2023-08-19' '24/08/2023' '2023-08-31' '2023-09-08'
 '2023-09-16' '2023-09-20' '2023-09-26' '2023-10-02' '03/10/2023']

==================================================
FILE 7
==================================================

Column: join_date
Missing: 34
Unparseable: 4
Out of range: 382
Unparseable values:
['2020-06-31' '00/00/2021' '2022-04-31']
Out-of-range values:
['2023-07-17' '2020-02-14' '2022-10-16' '2019-12-31' '2022-06-15'
 '2022-04-04' '21/04/2021' '2021-01-02' '2021-02-04' '2020-04-13']

==================================================
FILE 8
==================================================

Column: shipped_date
Missing: 5943
Unparseable: 819
Out of range: 258
Unparseable values:
['2024-02-30' '00/00/2024' '2024-06-31' '2024-04-31' '2025-06-31'
 '2025-02-30' '2025-04-31' '00/00/2025']
Out-of-range values:
['2025-07-01' 'Jul 1 2025' '01/07/2025' '2025-07-02' 'Jul 2 2025'
 '02/07/2025']

Column: delivered_date
Missing: 18841
Unparseable: 760
Out of range: 50
Unparseable values:
['2024-04-31' '00/00/2024' '2024-02-30' '2024-06-31' '2025-04-31'
 '2025-02-30' '2025-06-31' '00/00/2025']
Out-of-range values:
['2025-07-01' '2025-07-04' '2025-07-03' '2025-07-07' '2025-07-09'
 'Jul 11 2025' '2025-07-08' '13/07/2025' 'Jul 15 2025' '2025-07-26']

In [ ]:
#STAGE-3: DISTINCE VALUES OF CATEGORIAL COLUMNS to spot spelling variants.

In [11]:
for i, df in enumerate(dataset):
    for col in categorical_cols:
        if col in df.columns:
            values = df[col].dropna().astype(str).unique()
            normalized = pd.Series(values).str.strip().str.lower()

            if normalized.duplicated().any() or any(v != v.strip() for v in values):
                print(f"\nFile {i} | Column: {col}")
                print(values)

File 1 | Column: city
['PurPurPur' 'SaraiTandoKot' 'WalaSaraiBasti' 'ShahChakAbad' 'RahKila'
 'AliDera' 'KalanMian' 'SaraiJand' 'BastiPur' 'BastiJand' 'KHURDSHAHCHAK'
 'ThalShah' 'GulGarhNagar' 'BastiKhurdMari' 'GulDeraKhan' 'TandoKalan'
 'BhalMariAli' 'DhokNau' 'GarhMor' 'AbadGulNagar' 'RahBasti' 'AbadRah'
 'RahMianMian' 'KhurdPind' 'MianKalanGul' 'MianJandTando' 'KhurdBhal'
 'KilaWalaNagar' 'PindWalaJand' 'Sahiwal' 'Bahawalpur' 'RahLalKhurd'
 'JandDera' 'PurAli' 'PurMariKalan' 'MorMianGola' 'PurDeraPur' 'KhanPind'
 'saraikhanrah' 'AliMorBhal' 'TandoBhalLal' 'BastiNauKalan' 'GulBastiWala'
 'MorPind' 'TandoMorLal' 'MianPur' 'KhurdLalGul' 'AliBhal' 'MariGulKila'
 'ThalMianGola' 'JandRahBasti' 'KhanKilaRah' 'WalaMari' 'BastiJandKhurd'
 'GulBastiLal' 'Kohat' 'TandoLal' 'ThalNauGola' 'ThalTando' 'GolaKotTando'
 'PurTandoDhok' 'BhalDeraKhurd' 'KalanBhalAbad' 'NagarDhokSarai'
 'PINDKOTNAGAR' 'ThalWala' 'ThalBhalGul' 'TandoNau' 'DeraWalaGola'
 'PindDhok' 'ShahTando' 'ALIGULBASTI' 'KilaMor' 'BastiAbad'
 'KalanThalWala' 'NagarJand ' 'GarhRah' 'MariBhalMari' 'KhanRahGarh'
 'GolaAbad ' 'GarhNagar' 'MorGola' 'ChakBhalPur' 'GolaShahSarai'
 'GarhThalKalan' 'Peshawar' 'JandRahRah' 'NauKhan' 'AliMian' 'KhanGulGul'
 'KhanRahAli' 'DhokAliMari' 'KotWala' 'LalAbad' 'GulMari' 'BastiNauJand'
 'ChakNau' 'SaraiTandoSarai' 'KalanNau' 'lalsaraimari' 'KhanShah'
 'BastiPurBasti' 'Gwadar' 'KotKot' 'KotChak' 'PindKalanPind' 'ChakPur'
 'AliChakAli' 'Jacobabad' 'GarhThalWala' 'GolaRah' 'GarhNauKalan'
 'PurPind' 'SaraiLalBasti' 'DeraGola' 'Abbottabad' 'NauMari'
 'ShahGarhDera' 'NauGola' 'ChakGul' 'MorKalan' 'KhurdKhurd' 'DhokTando'
 'KalanDera' 'KalanPindGarh' 'PindRah' 'DhokAbad' 'LalPindDera'
 'DhokPindChak' 'kilatando' 'BastiGarhGola' 'NauSaraiShah' 'WalaThalDera'
 'NagarShahBasti' 'KhurdKalan' 'BHALKOT' 'MariKalan' 'BhalTando'
 'DhokDeraDera' 'MariGul' 'GulThalKalan' 'MorAli' 'MorShahAli' 'MariLal'
 'Jhang' 'NagarGarh' 'ThalShahPind' 'GarhMariMian' 'RahAliGul' 'ChakBasti'
 'MorDhok' 'KotDhokRah' 'NagarKila' 'KotGulMari' 'ShahJand' 'NauPindGarh'
 'AbadAli' 'GarhMari' 'NauAli' 'KhurdKalanThal' 'NauBhalKhan'
 'DhokNauBhal' 'KilaGarhPind' 'NauKalanPind' 'MorKhanMor' 'MariGola'
 'ShahKot' 'MorDera' 'PINDABAD' 'KilaBastiLal' 'KilaChakKila' 'NagarKhan'
 'GulShahAbad' 'ChakMian' 'WalaWala' 'ShahBastiGola' 'kalankot' 'Gujrat'
 'KhurdGulGul' 'khantandowala' 'MianJand' 'TandoNagar' 'KalanDhok'
 'NagarBasti' 'KhanMian' 'LalPindMian' 'PurDera' 'NagarThalNau'
 'DeraKalanJand' 'ThalNauSarai' 'KhurdKilaMor' 'MianAliJand'
 'KalanDeraKhurd' 'JandJandBhal' 'GarhAli' 'LalChakGola' 'MariDhokLal'
 'Sheikhupura' 'PurTando' 'ChakThalPind' 'ChakPindMor' 'DeraPurJand'
 'WalaBastiChak' 'DeraBhal' 'MianNagarDhok' 'MariBhalChak' 'KhanAli'
 'GarhPurSarai' 'rahnagarnau' 'JandKila' 'BhalGola' 'ShahSarai' 'MorKhurd'
 'TandoThal' 'NauGarhThal' 'NauPurKalan' 'LalDera' 'KotPindPind'
 'JandBhal' 'JandChakGarh' 'ThalPur' 'GolaDhok' 'PindDeraLal'
 'DERAKHURDKILA' 'GarhAbadTando' 'GolaShahBasti' 'AliKhan' 'MariAliRah'
 'MorNagar' 'LalMari' 'GulDera' 'MorGul' 'MorMor' 'WalaChak' 'DhokKhanLal'
 'KhanLal ' 'RahLalRah' 'MariPurAbad' 'BhalPur' 'DeraLalKhurd'
 'PurChakDera' 'DhokGulMian' 'ThalMian' 'ChakGarh' 'ShahKhurd' 'NagarChak'
 'GarhTando' 'ThalSaraiDhok' 'NauThalTando' 'MariMianKhurd' 'BastiGola'
 'ThalKhurd' 'DhokKhanMian' 'KotThalGola' 'GolaLalShah' 'Turbat'
 'KhurdAli' 'DeraBastiPur' 'ChakKalanNagar' 'DeraWala' 'JandBhalWala'
 'WalaAbad' 'WalaMorKila' 'GolaAbadNagar' 'DhokMian' 'AbadJandDera'
 'WalaKot' 'MianAliWala' 'KilaPur' 'GolaTando' 'NauThalMor' 'KalanTando'
 'WalaBastiPind' 'BastiMianPur' 'KhanGarhKalan' 'AliThalShah' 'DhokGarh'
 'KalanKilaMari' 'KilaAliKhan' 'GarhGulPind' 'Rawalpindi' 'KilaBhal'
 'Muzaffarabad' 'RahNagarGola' 'PindDeraNau' 'NauLal' 'WalaLalAbad'
 'MariMian' 'KalanJandKot' 'RahDhokDera ' 'Dera Ismail Khan ' 'AbadBasti'
 'ShahAliMor' 'GulKilaMari' 'MorMorChak' 'RahBhalShah' 'KhanBhal'
 'GarhBhal' 'TandoSarai' 'PindPindJand' 'BhalRah' 'DhokLalBasti'
 'MariGarhKot' 'LalJand' 'BastiMariBhal' 'NagarGarhKhan' 'AliGolaDhok'
 'PurBhalRah' 'ShahRah' 'BhalMariAbad' 'KhanWala' 'ChakKhurdGul'
 'ThalBastiWala' 'ChakSaraiMari' 'LalBasti' 'BastiThal' 'GarhKotRah'
 'ThalGarh' 'ThalKot' 'LalRah' 'DeraDhok' 'BhalChakJand' 'BastiShahRah '
 'RahDhok' 'GarhShah' 'DhokKhurd' 'PurGarhMari' 'KhanKotRah' 'Bannu'
 'RahGola' 'ThalAli' 'PurKila' 'DhokBhalMian' 'khurdpurtando'
 'GarhKalanKot' 'KhanSarai' 'DeraTandoMari' 'ChakMorKalan' 'MorShahKhurd'
 'RahPur' 'DeraGul' 'NagarGola' 'KilaGola' 'GulPurJand' 'GolaBastiPind'
 'Rahim Yar Khan' 'Islamabad' 'AbadPindSarai' 'DeraDeraDhok'
 'MariRahBasti' 'BastiKhurdNagar' 'MariWala' 'SaraiLalPur' 'WalaJand'
 'LalLalAli' 'KotGarh' 'NauGolaRah' 'PindGarhGarh' 'LalChakKhan'
 'ChakMari' 'GulGarh' 'MariChakGul' 'PurDhok' 'DhokKhan' 'GarhNagarTando'
 'KotBhal' 'RahMariSarai' 'DhokDhokAli' 'ThalKalan' 'KalanPur' 'GILGIT'
 'TandoLalLal' 'ThalMianMian' 'AliJand' 'PurDeraShah' 'MianAbad' 'Chiniot'
 'AbadKot' 'Mingora' 'PurLal' 'GulSarai' 'NauSarai' 'GolaKilaMian'
 'ShahMianAbad' 'WALARAH' 'ShahThalMor' 'KalanDhokGul' 'GulKhurdMari'
 'MariKhanDhok' 'PurThalMian' 'Sibi' 'Mirpur' 'NagarMian' 'Attock'
 'Skardu' 'NauShahGarh' 'dhokpindmor' 'MianKhurd' 'KotAliNau'
 'SaraiNagarKalan' 'Kasur' 'ThalThalNau' 'AliPur' 'BhalWala' 'WalaAli'
 'RahChak' 'NagarKotKila' 'DeraKalanKhan' 'Sukkur' 'NagarNauBhal'
 'khurddhok' 'AbadDhokKila' 'DhokMor' 'ThalThalThal' 'AliChakNau'
 'GolaGulBasti' 'gulwala' 'KalanNagar' 'PurMariJand' 'MianThal'
 'SaraiWala' 'AliKot' 'KotPurKot' 'MianMor' 'GulGul' 'Hyderabad'
 'BhalRahBhal' 'JandChak' 'GolaMariBhal' 'RahGul' 'ChakTando'
 'GarhShahPur' 'WalaShah' 'Sargodha' 'KalanKhurdKalan' 'NagarNagar'
 'MorLalNau' 'AliWalaLal' 'KhanMariThal' 'ThalKotAbad' 'NagarMari'
 'TandoJand' 'KhanRah' 'PindGola' 'ChakSaraiBasti' 'PindNau' 'RahPindJand'
 'ThalPurPind' 'WalaDhok' 'Lahore' 'TandoDeraGul' 'BhalChak' 'Khuzdar'
 'AliSaraiLal' 'PindGulDera' 'Quetta' 'KilaNau' 'BastiChak' 'BastiMor'
 'ChakWala' 'DeraAbad' 'NagarTando' 'PindLal' 'Jhelum' 'GarhKhan'
 'PurGulGul' 'SaraiGola' 'PurAbad' 'ThalKhan' 'AliGul' 'Mirpur Khas'
 'GarhLalThal' 'RahKalan' 'KilaWala' 'GolaKhan' 'KotKalanDhok'
 'NagarBastiGarh' 'ShahMorBhal' 'ChakPind' 'GulLal' 'TandoChakJand'
 'PindChakChak' 'MorAbad' 'AbadRahJand' 'GarhDera' 'ThalKhurdMari'
 'PindPurMor' 'GolaGarh' 'WalaChakKhan' 'KotKhurdDera' 'GarhThalGola'
 'TandoAbadKalan' 'TandoKalanChak' 'SaraiPur' 'GulTandoDhok'
 'AliKilaKalan' 'GolaNauDhok' 'WalaLal' 'MariKhurdGarh' 'JandGola'
 'NauAliGarh' 'KhurdChak' 'Mianwali' 'GulKhurdAli' 'DhokKotPur'
 'BhalKalan' 'DeraKotThal' 'WalaThal' 'DhokMianDera' 'MariAbad'
 'DhokBhalMor' 'DeraGolaGul' 'KhurdAliRah' 'AliKotGul' 'AliNagarGola'
 'BastiLalGul' 'GarhPindAli' 'JandShahRah' 'AliKalan' 'KhanGulNau'
 'DeraChak' 'SaraiMianKhan' 'RahWala' 'NagarKot' 'SaraiKalanBhal'
 'PurBhal ' 'LalTando' 'ShahKhurdKila' 'RahDeraLal' 'DhokWalaPind'
 'DhokChak' 'WalaDera' 'KhurdNagarAbad' 'LalKalan' 'Faisalabad' 'Sialkot'
 'PindShah' 'AbadPurPur ' 'RahBhal' 'SaraiDera' 'PindSaraiKhan' 'PindDera'
 'golasarai' 'GulShah' 'MianChakNagar ' 'DhokNagarChak' 'PurKalan'
 'Mardan' 'KilaTandoDhok' 'MianBasti' 'DeraRah' 'NagarKhurdBasti'
 'AliMianBhal' 'MariBhalBasti' 'MianShahRah' 'PurJand' 'DeraBasti '
 'SaraiMor' 'BhalBasti' 'BastiKalan' 'KhanShahAli' 'JandDhok'
 'AliDeraLal ' 'GarhAbad' 'DhokPur ' 'KalanGul' 'PurKilaBasti'
 'TandoNauLal' 'PurKhan' 'Larkana' 'KotKhan' 'Okara' 'MariPindKalan'
 'GulNagarTando' 'JandPurMor' 'GolaPind' 'NauBasti' 'AliJandKalan'
 'AbadBastiGola' 'GarhMianMari' 'PurPurThal' 'BastiNagarTando'
 'GulAbadAli' 'SaraiGarhGarh' 'KotLal' 'KhanDhokPind' 'PurKhurdBhal'
 'MariChakWala' 'NauNauLal' 'KilaKilaPind' 'KhanKila' 'KalanKhurdKhan'
 'SaraiSaraiRah' 'GulKilaPind' 'ChakGola' 'ChakMianShah' 'Gujranwala'
 'NauNagarKot' 'GarhKilaDhok' 'ThalGola' 'Multan' 'LalWalaNagar'
 'MorRahKhan' 'ChakSaraiDhok' 'ShahAli' 'NauWala' 'RahKhurdJand' 'MianNau'
 'TandoWala' 'GulGarhDhok' 'TandoMian' 'ThalPindGarh' 'TandoGul' 'Karachi'
 'PindThalJand' 'NauPind' 'Dera Ghazi Khan' 'DeraJand' 'WalaWalaTando'
 'GulGola' 'JandBasti' 'KalanKotKhurd' 'PurMian' 'NagarSaraiWala'
 'JandKhan' 'DhokKalan' 'DeraDera' 'AbadKhanKhan' 'GulGolaKhurd'
 'NagarPurMari' 'NauKotRah' 'PindMorPur' 'KhurdPur' 'AliRahDhok'
 'AbadShahGul' 'PurMariMor' 'KilaSarai' 'GarhKila' 'Thatta'
 'KhurdBastiGola' 'Mansehra' 'WalaKila' 'NAWABSHAH' 'NagarTandoRah'
 'RahDera' 'AliKilaGul' 'DeraAli' 'GarhDhok' 'WalaNagar' 'MianKilaThal']

File 1 | Column: province
['Sindh' 'Punjab' 'Balochistan' 'Khyber Pakhtunkhwa' 'KP'
 'Gilgit-Baltistan' 'Baluchistan' 'sindh' 'punjab' 'Azad Kashmir'
 'Khyber Pakhtunkhwa ' 'BALOCHISTAN' 'SINDH' 'Sind' 'PUNJAB' 'Panjab'
 'KPK' 'Gilgit Baltistan' 'Islamabad' 'GB' 'Azad Jammu & Kashmir']

File 2 | Column: order_status
['DELIVERD' 'Delivered' 'Completed' 'Cancelled' 'Complete' 'RETURNED'
 'DELIVERED' 'delivered' 'Returned' 'cancelled' 'Canceled' 'Cancelled '
 'Shipped' 'CANCELLED' 'returned' 'In Transit' 'IN TRANSIT' 'Return'
 'in transit' 'In-Transit']

File 2 | Column: channel
['Website' 'App' 'Web' 'Mobile Web' 'web' 'APP' 'app' 'Mobile web'
 'mobile web' 'WEB' 'Mobile App' 'MWeb']

File 4 | Column: payment_method
['COD' 'JazzCash' 'Debit Card' 'bank transfer' 'cod' 'Cash On Delivery'
 'COD ' 'EasyPaisa' 'Card' 'Bank Transfer' 'Easy Paisa' 'Jazzcash'
 'Cash on Delivery' 'Jazz Cash' 'CARD' 'card' 'EASYPAISA' 'Easypaisa'
 'Bank Trf' 'BANK TRANSFER' 'JAZZCASH' 'Credit/Debit Card']

File 4 | Column: payment_status
['Paid' 'Cancelled' 'Complete' 'REFUNDED' 'Success' 'paid' 'PAID'
 'Refunded' 'Canceled' 'Refund' 'CANCELLED' 'cancelled' 'Cancelled '
 'Pending' 'refunded' 'PENDING' 'pending']

File 5 | Column: category
['Mobile & Accessories' 'Footwear' 'Fashion' 'Sports' 'Automotive'
 'Health and Wellness' 'Elec.' 'Auto' 'Car Accessories' 'Electronics'
 'Food & Grocery' 'Home & Kitchen ' 'Toys & Games' 'HEALTH & WELLNESS '
 'Health & Wellness ' 'Mobile and Accessories' 'Electronics ' 'Grocery'
 'Home & Kitchen' 'Beauty & Personal Care' 'beauty & personal care'
 'Clothing' 'Beauty' 'sports & outdoors' 'FOOTWEAR ' 'Toys and Games'
 'FASHION ' 'Shoes' 'BEAUTY & PERSONAL CARE ' 'Mobile Acc.'
 'Electronic Items' 'Toys & Games ' 'MOBILE & ACCESSORIES ' 'electronics'
 'Sports & Outdoors' 'Fashion & Apparel' 'books & stationery'
 'SPORTS & OUTDOORS ' 'Health & Wellness' 'Fashion '
 'Beauty & Personal Care ' 'Automotive ' 'footwear' 'Groceries'
 'Beauty and Personal Care' 'Home and Kitchen' 'Books & Stationery'
 'mobile & accessories' 'Toys' 'Health' 'Stationary' 'TOYS & GAMES '
 'Sports and Outdoors' 'HOME & KITCHEN ' 'ELECTRONICS ' 'Books' 'GROCERY '
 'Sports & Outdoors ' 'Mobile & Accessories ' 'Mobiles'
 'health & wellness' 'fashion' 'Home&Kitchen' 'automotive' 'grocery'
 'Footwear ' 'Personal Care' 'Books and Stationery' 'toys & games'
 'Books & Stationery ' 'Grocery ' 'BOOKS & STATIONERY ' 'home & kitchen'
 'AUTOMOTIVE ']

File 6 | Column: return_status
['Refunded' 'REFUNDED' 'Approved' 'Refund' 'refunded' 'Rejected'
 'approved' 'APPROVED' 'rejected' 'Declined']

File 6 | Column: return_reason
['Not as described' 'Size/fit issue' 'Quality issue' 'not as described'
 'Wrong item delivered' 'Wrong colour' 'Damaged product'
 'Not as Described' 'size/fit' "Doesn't fit" 'Late delivery'
 'Changed mind' 'Missing parts' 'damaged' 'Item damaged'
 'no longer needed' 'DAMAGED PRODUCT' 'bad quality' 'Colour mismatch'
 'quality' 'different from picture' 'Wrong size' 'changed my mind'
 'Delivered late' 'size issue' 'incomplete' 'Poor quality'
 'Change of mind' 'Wrong Item' 'color mismatch' 'missing part'
 'colour different' 'received wrong product' 'late' 'wrong item'
 'too late' 'Parts missing']

File 8 | Column: delivery_status
['DELIVERD' 'Delivered' 'delivered' 'RTO' 'Completed' 'DELIVERED'
 'returned to seller' 'Returned to Seller' 'Complete' 'Return to Seller'
 'In Transit' 'Shipped' 'In-Transit' 'IN TRANSIT' 'in transit']

File 8 | Column: courier
['M&P' 'Leopards' 'POSTEX' 'TCS Express' 'TCS' 'PostEx' 'tcs' 'Postex'
 'BlueEx' 'Trax' 'MnP' 'LEOPARDS' 'T.C.S' 'Leopard Courier' 'blueex'
 'leopards' 'M & P' 'TRAX' 'm&p' 'trax' 'Blue-Ex' 'Blue EX']

In [ ]:
#CHECK OUTLIERS ACROSS ALL 9 FILES -> thesee are the files and columns that we need to check for the outliers

In [15]:
for i, df in enumerate(dataset):
    print(f"\nFile {i}: {df.columns.tolist()}")

File 0: ['customer_id', 'full_name', 'email', 'phone', 'gender', 'registration_date', 'city_id', 'birth_year']

File 1: ['city_id', 'city', 'province', 'region', 'latitude', 'longitude', 'population_tier']

File 2: ['order_id', 'customer_id', 'order_date', 'order_status', 'ship_city_id', 'order_total', 'discount_code', 'channel']

File 3: ['order_item_id', 'order_id', 'product_id', 'seller_id', 'quantity', 'unit_price', 'discount_amount']

File 4: ['payment_id', 'order_id', 'payment_method', 'payment_status', 'amount', 'payment_date']

File 5: ['product_id', 'product_name', 'category', 'sub_category', 'brand', 'list_price', 'cost_price', 'weight_kg', 'seller_id']

File 6: ['return_id', 'order_item_id', 'return_date', 'return_reason', 'return_status', 'refund_amount']

File 7: ['seller_id', 'seller_name', 'join_date', 'seller_tier', 'city_id', 'rating']

File 8: ['shipment_id', 'order_id', 'courier', 'shipped_date', 'delivered_date', 'shipping_fee', 'delivery_status']

In [ ]:
#we have to identify ourselves as to which fields can have outliers

In [ ]:
#possibility:  File 0: birth_year, File 1: latitude, longitude, File 2: order_total,  #File 3: quantity, unit_price,discount_amount
               #File 4: amount, File 5: list_price, cost_price, weight_kg, File 6: refund_amount, File 7: rating
               # File 8: Shipping Fee

In [ ]:
#ORPHAN KEYS

In [16]:
relationships = [
    (2, 'customer_id', 0, 'customer_id'),       # Orders → Customers
    (2, 'ship_city_id', 1, 'city_id'),          # Orders → Cities
    (3, 'order_id', 2, 'order_id'),             # Order items → Orders
    (3, 'product_id', 5, 'product_id'),         # Order items → Products
    (3, 'seller_id', 7, 'seller_id'),            # Order items → Sellers
    (4, 'order_id', 2, 'order_id'),             # Payments → Orders
    (5, 'seller_id', 7, 'seller_id'),            # Products → Sellers
    (6, 'order_item_id', 3, 'order_item_id'),   # Returns → Order items
    (7, 'city_id', 1, 'city_id'),               # Sellers → Cities
    (8, 'order_id', 2, 'order_id')              # Shipments → Orders
]

for child_idx, child_col, parent_idx, parent_col in relationships:
    child = dataset[child_idx]
    parent = dataset[parent_idx]

    orphan_mask = (
        child[child_col].notna() &
        ~child[child_col].isin(parent[parent_col])
    )

    print(
        f"File {child_idx} ({child_col}) → "
        f"File {parent_idx} ({parent_col}): "
        f"{orphan_mask.sum()} orphan rows"
    )

    if orphan_mask.any():
        print(child.loc[orphan_mask, [child_col]].head())

File 2 (customer_id) → File 0 (customer_id): 330 orphan rows
    customer_id
197      C98859
455      C96770
677      C96644
814      C96819
913      C91906
File 2 (ship_city_id) → File 1 (city_id): 0 orphan rows
File 3 (order_id) → File 2 (order_id): 0 orphan rows
File 3 (product_id) → File 5 (product_id): 932 orphan rows
    product_id
127     P96243
167     P97524
234     P93742
554     P90073
561     P99790
File 3 (seller_id) → File 7 (seller_id): 0 orphan rows
File 4 (order_id) → File 2 (order_id): 0 orphan rows
File 5 (seller_id) → File 7 (seller_id): 0 orphan rows
File 6 (order_item_id) → File 3 (order_item_id): 139 orphan rows
    order_item_id
54        OI94118
88        OI92084
316       OI99844
471       OI90501
898       OI95135
File 7 (city_id) → File 1 (city_id): 0 orphan rows
File 8 (order_id) → File 2 (order_id): 0 orphan rows

In [ ]:
#To check records with missing relationship ids, we check missing foreign keys

In [17]:
#This identifies records with missing relationship IDs separately from orphan keys

for child_idx, child_col, parent_idx, parent_col in relationships:
    df = dataset[child_idx]
    missing = df[child_col].isna().sum()

    print(f"File {child_idx} | {child_col} | Missing IDs: {missing}")

File 2 | customer_id | Missing IDs: 0
File 2 | ship_city_id | Missing IDs: 6516
File 3 | order_id | Missing IDs: 0
File 3 | product_id | Missing IDs: 0
File 3 | seller_id | Missing IDs: 0
File 4 | order_id | Missing IDs: 0
File 5 | seller_id | Missing IDs: 0
File 6 | order_item_id | Missing IDs: 0
File 7 | city_id | Missing IDs: 0
File 8 | order_id | Missing IDs: 0

In [ ]:
#Possible duplicate customers and products

In [19]:
#This finds records matching on all four fields. Treat them as possible duplicates to investigate, not automatically confirmed duplicates.
#CUSTOMERS: 
customers = dataset[0].copy()

customers['normalized_name'] = (
    customers['full_name'].str.strip().str.lower()
)
customers['normalized_email'] = customers['email'].str.strip().str.lower()
customers['normalized_phone'] = (
    customers['phone'].astype('string').str.replace(r'\D', '', regex=True)
)

duplicate_customers = customers[
    customers.duplicated(
        subset=['normalized_email', 'normalized_phone',
                'birth_year', 'normalized_name'],
        keep=False
    )
]

duplicate_customers.sort_values('normalized_email')

,customer_id,full_name,email,phone,gender,registration_date,city_id,birth_year,normalized_name,normalized_email,normalized_phone
43555,C043556,Ahmed Akhtar,AHMED.AKHTAR4584@GMAIL.COM,03437275239,NaN,2024-01-29,407.0,1993.0,ahmed akhtar,ahmed.akhtar4584@gmail.com,03437275239
40740,C040741,Ahmed Akhtar,ahmed.akhtar4584@gmail.com,0343-7275239,M,2024-01-11,407.0,1993.0,ahmed akhtar,ahmed.akhtar4584@gmail.com,03437275239
42680,C042681,Ahmed Ansari,ahmed.ansari8680@gmail.com,0320-8896124,male,Jun 5 2025,450.0,1990.0,ahmed ansari,ahmed.ansari8680@gmail.com,03208896124
28913,C028914,Ahmed Ansari,ahmed.ansari8680@gmail.com,0320-8896124,M,2024-10-01,450.0,1990.0,ahmed ansari,ahmed.ansari8680@gmail.com,03208896124
42668,C042669,Ahmed Butt,ahmed.butt6659@gmail.com,03436439180,NaN,2025-02-20,501.0,1995.0,ahmed butt,ahmed.butt6659@gmail.com,03436439180
...,...,...,...,...,...,...,...,...,...,...,...
41181,C041182,Laiba Chaudhry,NaN,0335 1601291,F,2025-06-08,617.0,1998.0,laiba chaudhry,NaN,03351601291
42517,C042518,Laiba Chaudhry,NaN,0335-1601291,F,2024-02-08,617.0,1998.0,laiba chaudhry,NaN,03351601291
43106,C043107,Hussain Siddiqui,NaN,0342-4907675,M,2024-04-19,614.0,1989.0,hussain siddiqui,NaN,03424907675
43878,C043879,Ayesha Nawaz,NaN,03165770670,f,20/03/2025,450.0,1982.0,ayesha nawaz,NaN,03165770670
44100,C044101,Rabia Mirza,NaN,0327-5474259,NaN,2024-11-08,347.0,1998.0,rabia mirza,NaN,03275474259

In [20]:
#PRODUCTS

products = dataset[5].copy()

products['normalized_name'] = products['product_name'].str.strip().str.lower()
products['normalized_brand'] = products['brand'].str.strip().str.lower()

duplicate_products = products[
    products.duplicated(
        subset=['normalized_name', 'normalized_brand'],
        keep=False
    )
]

duplicate_products.sort_values(['normalized_name', 'normalized_brand'])

,product_id,product_name,category,sub_category,brand,list_price,cost_price,weight_kg,seller_id,normalized_name,normalized_brand
1406,P01407,BeauPro Trimmer Y812,Beauty & Personal Care,Beauty Premium,BeauPro,400,188.0,0.62,S0057,beaupro trimmer y812,beaupro
3164,P03165,BeauPro Trimmer Y812,BEAUTY & PERSONAL CARE,Beauty Premium,BeauPro,393,188.0,0.62,S0193,beaupro trimmer y812,beaupro
62,P00063,ElecPro Power Strip D878,electronics,NaN,ElecPro,6400,5574.0,2.21,S0329,elecpro power strip d878,elecpro
3084,P03085,ElecPro Power Strip D878,ELECTRONICS,Electronics Essentials,ElecPro,6323,9484.0,2.21,S0134,elecpro power strip d878,elecpro
2215,P02216,ElecPro Power Strip U248,Electronic Items,Electronics Essentials,ElecPro,55470,83205.0,NaN,S0378,elecpro power strip u248,elecpro
3089,P03090,ElecPro Power Strip U248,Elec.,Electronics Essentials,ElecPro,54644,81966.0,1.27,S0251,elecpro power strip u248,elecpro
871,P00872,Generic Laptop Stand P215,Electronics,Electronics Premium,Generic,10580,8314.0,1.64,S0329,generic laptop stand p215,generic
3149,P03150,Generic Laptop Stand P215,electronics,Electronics Premium,Generic,10805,8314.0,1.64,S0349,generic laptop stand p215,generic
1366,P01367,Generic Polo Shirt X880,Fashion,Fashion Premium,Generic,5220,2696.0,0.54,S0286,generic polo shirt x880,generic
3124,P03125,Generic Polo Shirt X880,Clothing,Fashion Premium,Generic,5254,2696.0,0.54,S0286,generic polo shirt x880,generic
1376,P01377,Generic Seat Cover A413,automotive,Automotive Basics,Generic,2110,1423.0,1.07,S0226,generic seat cover a413,generic
3079,P03080,Generic Seat Cover A413,AUTOMOTIVE,Automotive Basics,Generic,2073,1423.0,1.07,S0241,generic seat cover a413,generic
2348,P02349,Generic Storage Box C617,HOME & KITCHEN,Home Premium,Generic,5810,4492.0,NaN,S0236,generic storage box c617,generic
3109,P03110,Generic Storage Box C617,Home & Kitchen,Home Premium,Generic,5858,4492.0,4.30,S0122,generic storage box c617,generic
2897,P02898,GrocPro Spice Box D133,Grocery,NaN,GrocPro,450,400.0,1.49,S0139,grocpro spice box d133,grocpro
3085,P03086,GrocPro Spice Box D133,Food & Grocery,Grocery Premium,GrocPro,446,400.0,1.49,S0409,grocpro spice box d133,grocpro
2491,P02492,NexusChoice Lawn Suit 3pc F238,Fashion,Fashion Essentials,NexusChoice,2970,1401.0,0.38,S0119,nexuschoice lawn suit 3pc f238,nexuschoice
3170,P03171,NexusChoice Lawn Suit 3pc F238,Fashion,Fashion Essentials,NexusChoice,3055,1401.0,0.38,S0412,nexuschoice lawn suit 3pc f238,nexuschoice
1701,P01702,NexusChoice Selfie Stick C307,Mobile & Accessories,Mobile Essentials,NexusChoice,Rs. 520,321.0,0.22,S0122,nexuschoice selfie stick c307,nexuschoice
3108,P03109,NexusChoice Selfie Stick C307,Mobile and Accessories,NaN,NexusChoice,522,321.0,0.22,S0164,nexuschoice selfie stick c307,nexuschoice
1904,P01905,Orion Air Fryer C308,Elec.,NaN,Orion,8340,7292.0,1.33,S0347,orion air fryer c308,orion
3180,P03181,Orion Air Fryer C308,Electronics,Electronics Essentials,Orion,8429,7292.0,1.33,S0038,orion air fryer c308,orion
1507,P01508,Orion Bluetooth Speaker Z255,Elec.,Electronics Basics,Orion,27500,23772.0,3.69,S0357,orion bluetooth speaker z255,orion
3102,P03103,Orion Bluetooth Speaker Z255,Electronic Items,Electronics Basics,Orion,27228,23772.0,3.69,S0357,orion bluetooth speaker z255,orion
1831,P01832,Orion Doll House L642,Toys,Toys Basics,Orion,1070,655.0,0.79,S0219,orion doll house l642,orion
3110,P03111,Orion Doll House L642,Toys,Toys Basics,Orion,1046,655.0,NaN,S0067,orion doll house l642,orion
2538,P02539,Orion Moisturizer R840,Beauty & Personal Care,Beauty Basics,NaN,3370,1634.0,0.38,S0078,orion moisturizer r840,NaN
3195,P03196,Orion Moisturizer R840,Beauty & Personal Care,Beauty Basics,NaN,3391,1634.0,0.38,S0306,orion moisturizer r840,NaN
711,P00712,Zeta Abaya L431,fashion,NaN,Zeta,4140,NaN,0.37,S0308,zeta abaya l431,zeta
3185,P03186,Zeta Abaya L431,Fashion,Fashion Essentials,Zeta,4020,1992.0,0.37,S0338,zeta abaya l431,zeta
1799,P01800,Zeta Laptop Stand C611,Electronics,Electronics Premium,Zeta,12040,10615.0,-1.00,S0411,zeta laptop stand c611,zeta
3161,P03162,Zeta Laptop Stand C611,Electronics,Electronics Premium,Zeta,12070,10615.0,3.08,S0273,zeta laptop stand c611,zeta
801,P00802,ZETA STORAGE BOX F532,home & kitchen,Home Premium,Zeta,3760,2419.0,3.15,S0001,zeta storage box f532,zeta
3104,P03105,ZETA STORAGE BOX F532,Home & Kitchen,Home Premium,Zeta,3793,2419.0,3.15,S0354,zeta storage box f532,zeta
252,P00253,Zeta USB-C Cable Z427,Mobile & Accessories,Mobile Essentials,Zeta,330,171.0,0.46,S0164,zeta usb-c cable z427,zeta
3081,P03082,Zeta USB-C Cable Z427,Mobile and Accessories,Mobile Essentials,Zeta,339,171.0,0.46,S0316,zeta usb-c cable z427,zeta
5,P00006,Zeta Yoga Mat M69,Health and Wellness,Health Essentials,Zeta,2010,1238.0,0.39,S0169,zeta yoga mat m69,zeta
3139,P03140,Zeta Yoga Mat M69,Health & Wellness,NaN,Zeta,2012,1238.0,0.39,S0296,zeta yoga mat m69,zeta

In [ ]:
#Consistency checks

In [33]:
#CHANGED DATATYPE INTO NUMERIC
items['quantity'] = pd.to_numeric(items['quantity'], errors='coerce')

items['unit_price'] = pd.to_numeric(
    items['unit_price'].astype(str).str.replace(r'Rs\.?\s*|,', '', regex=True),
    errors='coerce'
)

items['discount_amount'] = pd.to_numeric(
    items['discount_amount'], errors='coerce'
)

In [42]:
items['line_total'] = (
    items['quantity'] * items['unit_price']
    - items['discount_amount']
)
calculated_totals = items.groupby('order_id')['line_total'].sum()
orders['order_total'] = pd.to_numeric(
    orders['order_total'].astype(str).str.replace(r'Rs\.?\s*|,', '', regex=True),
    errors='coerce'
)
orders['difference'] = orders['order_total'] - orders['calculated_total']
orders[orders['difference'].abs() > 0.01][
    ['order_id', 'order_total', 'calculated_total', 'difference']
]

        order_id  order_total  calculated_total  difference
2       O0083748         2362            2023.0       339.0
16      O0042918         1476             561.0       915.0
21      O0025356        15682               0.0     15682.0
24      O0051382         4590            3623.0       967.0
41      O0130009         3080            1156.0      1924.0
...          ...          ...               ...         ...
163160  O0091604         3406            1060.0      2346.0
163173  O0121296         6882               0.0      6882.0
163188  O0096974         5197            3846.0      1351.0
163195  O0014965         3271               0.0      3271.0
163199  O0032135          506               0.0       506.0

[33686 rows x 4 columns]

In [ ]:
#The table shows that 33,686 orders have totals that don't match the totals calculated from their order items.

In [40]:
(orders['difference'].abs() > 0.01).sum()

np.int64(33686)

In [ ]:
#B. Does discount_code map to a percentage?

In [24]:

#Which discount codes exist and how often they appear
dataset[2]['discount_code'].value_counts(dropna=False)

discount_code
NaN        112059
SAVE15       7846
SAVE10       7352
SAVE20       6763
SAVE40       5898
SAVE30       5246
SAVE5        5066
SAVE25       4112
SAVE50       2675
Save15        369
 SAVE15       348
save20        343
 SAVE10       336
Save10        334
save15        330
save10        322
 SAVE20       316
save40        292
Save20        286
 SAVE40       260
 SAVE5        258
Save40        255
save5         236
Save30        236
save30        235
 SAVE30       231
Save5         230
Save25        201
save25        192
 SAVE25       188
 SAVE50       162
Save50        122
save50        101
Name: count, dtype: int64

In [ ]:
#It tells you how many times each discount code appears in the orders dataset, including missing values (NaN).

In [47]:
items = dataset[3]

print(items[['quantity', 'unit_price', 'discount_amount']].head(10))

  quantity unit_price  discount_amount
0        1  Rs. 2,290              0.0
1        1       5850              0.0
2        1       1900              0.0
3        1       2180              0.0
4        1       2100              0.0
5        1       6340              0.0
6        2       1840              0.0
7        2       3570              NaN
8        1       1340            268.0
9        1        650              0.0

In [48]:
#Prepared items data by converting quantity, unit_price and discount into numeric values and Calculated gross amount and discount percentage
items = dataset[3].copy()

items['quantity'] = pd.to_numeric(items['quantity'], errors='coerce')
items['unit_price'] = pd.to_numeric(
    items['unit_price'].astype(str).str.replace(r'Rs\.?\s*|,', '', regex=True),
    errors='coerce'
)

items['discount_amount'] = pd.to_numeric(
    items['discount_amount'], errors='coerce'
)

items['gross_amount'] = items['quantity'] * items['unit_price']

items['discount_percentage'] = (
    items['discount_amount'] / items['gross_amount'] * 100
)

items[['quantity', 'unit_price', 'discount_amount',
       'gross_amount', 'discount_percentage']].head(10)

   quantity  unit_price  discount_amount  gross_amount  discount_percentage
0       1.0      2290.0              0.0        2290.0                  0.0
1       1.0      5850.0              0.0        5850.0                  0.0
2       1.0      1900.0              0.0        1900.0                  0.0
3       1.0      2180.0              0.0        2180.0                  0.0
4       1.0      2100.0              0.0        2100.0                  0.0
5       1.0      6340.0              0.0        6340.0                  0.0
6       2.0      1840.0              0.0        3680.0                  0.0
7       2.0      3570.0              NaN        7140.0                  NaN
8       1.0      1340.0            268.0        1340.0                 20.0
9       1.0       650.0              0.0         650.0                  0.0

In [49]:
items['discount_percentage'].round(2).value_counts().sort_index()

discount_percentage
-130.00       1
-129.98       1
-50.02        1
-50.01        1
-50.00       12
             ..
 14000.53     1
 14001.86     1
 14002.09     1
 36373.52     1
 inf         83
Name: count, Length: 532, dtype: int64

In [50]:
#Checked invalid values:

print("Zero or missing gross amounts:", (items['gross_amount'].isna() | (items['gross_amount'] == 0)).sum())
print("Negative discounts:", (items['discount_amount'] < 0).sum())
print("Discounts greater than gross amount:", (items['discount_amount'] > items['gross_amount']).sum())

Zero or missing gross amounts: 1295
Negative discounts: 0
Discounts greater than gross amount: 1586

In [51]:
#Filtered invalid amounts
valid = items[
    (items['gross_amount'] > 0) &
    (items['discount_amount'] >= 0) &
    (items['discount_amount'] <= items['gross_amount'])
].copy()

valid['discount_percentage'] = (
    valid['discount_amount'] / valid['gross_amount'] * 100
).round().astype(int)

valid['discount_percentage'].value_counts().sort_index()

discount_percentage
0     190214
1          3
5       9858
10     14051
15     14882
20     13049
25      7900
28         1
30     10052
40     14319
50      6578
Name: count, dtype: int64

In [55]:
#Compared percentage patterns with codes

check = dataset[2][['order_id', 'discount_code']].merge(
    valid[['order_id', 'discount_percentage']],
    on='order_id',
    how='inner'
)

check.groupby(['discount_code', 'discount_percentage']).size().unstack(fill_value=0)

discount_percentage,0%%,1%%,10%%,15%%,20%%,25%%,28%%,30%%,40%%,5%%,50%%
discount_code,,,,,,,,,,,
SAVE10,0,0,551,0,0,0,0,0,0,0,0
SAVE15,2,0,0,566,0,0,0,0,0,0,0
SAVE20,2,0,0,0,546,0,0,0,0,0,0
SAVE25,1,0,0,0,0,330,0,0,0,0,0
SAVE30,1,0,0,0,0,0,0,400,0,0,0
SAVE40,1,0,0,0,0,0,0,0,545,0,0
SAVE5,2,0,0,0,0,0,0,0,0,434,0
SAVE50,1,0,0,0,0,0,0,0,0,0,358
SAVE10,56,0,12666,0,0,0,0,0,0,0,0
SAVE15,39,0,0,13400,0,0,0,0,0,0,0
SAVE20,40,0,0,0,11710,0,0,0,0,0,0
SAVE25,23,0,0,0,0,7052,0,0,0,0,0
SAVE30,49,0,0,0,0,0,0,9074,0,0,0
SAVE40,58,0,0,0,0,0,0,0,12932,0,0
SAVE5,28,0,0,0,0,0,0,0,0,8802,0
SAVE50,21,2,0,0,0,0,1,0,0,0,5867
Save10,0,0,570,0,0,0,0,0,0,0,0
Save15,3,0,0,647,0,0,0,0,0,0,0
Save20,2,0,0,0,463,0,0,0,0,0,0
Save25,1,0,0,0,0,340,0,0,0,0,0
Save30,2,0,0,0,0,0,0,398,0,0,0
Save40,2,0,0,0,0,0,0,0,523,0,0
Save5,2,0,0,0,0,0,0,0,0,381,0
Save50,3,0,0,0,0,0,0,0,0,0,253
save10,4,0,535,0,0,0,0,0,0,0,0
save15,2,0,0,586,0,0,0,0,0,0,0
save20,2,0,0,0,605,0,0,0,0,0,0
save25,3,0,0,0,0,335,0,0,0,0,0
save30,0,0,0,0,0,0,0,410,0,0,0
save40,2,0,0,0,0,0,0,0,609,0,0
save5,1,0,0,0,0,0,0,0,0,411,0
save50,0,0,0,0,0,0,0,0,0,0,229